In [1]:
### ARRAYS in NUMPY

#numpy arrays can be created using datatypes like 

In [2]:
import numpy as np


In [11]:
a=np.array([1,2,3,4]) # rank one array

In [12]:
a

array([1, 2, 3, 4])

In [13]:
b=np.array([[1,2,3],[4,5,6]]) #rank two array

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
c=np.array((1,2,3))

In [16]:
c

array([1, 2, 3])

In [17]:
### Accessing the Array Elements   # a[rows,columns]

In [18]:
aa=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [19]:
aa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
aa[1,2]   ### picking one element

7

In [24]:
aa[:,1:] #### picking all the rows and elements preceding column 1

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [26]:
aa[1::2,1::2]  ### picking elemnts from row one and column one to end with alternate columns and rows

array([[6, 8]])

In [27]:
### Basic array operations

In [28]:
import numpy as np

In [29]:
a=np.array([[1,2,3],[4,5,6]])

In [30]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
b=np.array([[3,4,5],[7,8,9]])

In [32]:
b

array([[3, 4, 5],
       [7, 8, 9]])

In [34]:
a+1    ### adding 1 to each element in an array

array([[2, 3, 4],
       [5, 6, 7]])

In [35]:
a-2   ### subtracting 2 to each element in an array

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [36]:
### unary operations

In [38]:
a.sum() ### sum of all the elements in an array

21

In [40]:
b=np.array([[4,5,6],[7,89,5]])

In [42]:
a+b     ### binary operation


array([[ 5,  7,  9],
       [11, 94, 11]])

In [43]:
### ndarray

In [44]:
arr=np.array([[1,2,3],[4,5,6]])

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
print("array is of type",type(arr))

array is of type <class 'numpy.ndarray'>


In [47]:
print("no of dimensions",arr.ndim)

no of dimensions 2


In [48]:
print("shape of array",arr.shape)

shape of array (2, 3)


In [49]:
print("size of the array",arr.size)

size of the array 6


In [50]:
print("array stores elements of type",arr.dtype)

array stores elements of type int32


In [51]:
### Array creation

In [52]:
a=[1,2,3,4,5]

In [55]:
for i in a:
    print(i)

1
2
3
4
5


In [62]:
print("array in array function",end=" ")
for i in range (0,5):
    print(a[i],end=" ")

array in array function 1 2 3 4 5 

In [63]:
###  Reshaping the array

In [64]:
import numpy as np

In [65]:
array=np.arange(8)

In [66]:
array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [67]:
array=np.arange(8).reshape(2,4)    #2rows and 4 colunms

In [68]:
array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [69]:
array=np.arange(8).reshape(4,2)

In [70]:
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [71]:
array=np.arange(8).reshape(2,2,2)

In [72]:
array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])